Repository cortexproject/auth-gateway, pull requests merged in 2024-06, with the labels that each got.

#39 Fix(auth): use crypto/subtle to compare strings
  gateway/middleware.go
Labels: size/S

#40 passthrough
  gateway/config.go
  gateway/gateway_test.go
  gateway/middleware.go
Labels: size/M

#41 Upgrade to go 1.22
  .github/workflows/build-test.yml
  go.mod
Labels: size/XS
